// Generated by CoffeeScript 1.3.3
(function() {
  var Data, UI, _;

  _ = require("lib/underscore.js");

  UI = require("ui.js");

  console.log('UI:', UI);

  Data = require("data.js");

  console.log('Data:', Data);

  Data.getRSS(function(data) {
    console.log(data);
    UI.components['tableView1'].setData(data);
    return UI.components['win1'].remove(UI.components['label1']);
  });

}).call(this);
